### ISSUE TITLE
Duda con relaciones de Follow en pioller

### ISSUE THREAD

**Issue by MortizDX** [IIC2513-2017-1/pioller#2]
Viendo el commit en que se agregaron las relaciones para tener seguidores en la aplicación, no me queda claro como lo establecen en el modelo del usuario.

```
has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
```
Creo que con esto está estableciendo dos tablas nuevas con las nuevas llaves foráneas.

```
has_many :followers, through: :follower_relationships, source: :follower
has_many :following, through: :following_relationships, source: :following
```
Pero con esto me confunde más ¿qué hace esta porción? O más bien ¿qué hacen ambas porciones de código?

**Comment by rasaffie** [comment]
IIC2513-2017-1/syllabus#14
